#!/bin/bash

echo -e "\nRunning: pep8 ... \n"

# Ignoring autogenerated files
#  -- Migration directories
# Ignoring error codes
#  -- E128 continuation line under-indented for visual indent
#  -- E225 missing whitespace around operator
#  -- E501 line too long

pep8 --ignore=E128,E225,E501 slugify test.py setup.py

echo -e "Done.\n"
