[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "python-slugify"
dynamic = ["version"]
description = "A Python slugify application that also handles Unicode"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [{name = "Val Neekman", email = "info@neekware.com"}]
dependencies = ["text-unidecode>=1.3"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.optional-dependencies]
unidecode = ["Unidecode>=1.1.1"]
anyascii = ["anyascii>=0.3.2"]

[project.scripts]
slugify = "slugify.__main__:main"

[project.urls]
Homepage = "https://github.com/un33k/python-slugify"
Issues = "https://github.com/un33k/python-slugify/issues"
Changelog = "https://github.com/un33k/python-slugify/blob/master/CHANGELOG.md"

[tool.setuptools]
packages = ["slugify"]
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "slugify.__version__.__version__"}

[tool.setuptools.package-data]
slugify = ["py.typed"]


# coverage
# --------

[tool.coverage.run]
relative_files = true
parallel = true
branch = true
source = [
    "slugify",
    "test",
]

[tool.coverage.paths]
source = [
    "src",
    "*/site-packages",
]

[tool.coverage.report]
skip_covered = true
fail_under = 97


# mypy
# ----

[tool.mypy]
packages = "slugify"
strict = true
sqlite_cache = true


# pytest
# ------

[tool.pytest.ini_options]
testpaths = ["test.py", "test_release.py"]
addopts = "--color=yes"
filterwarnings = [
    "error",
]
