name: CI

# Run on push only for dev/sandbox
# Otherwise it may trigger concurrently `push & pull_request` on PRs.
on:
  push:
    branches:
      - ci
      - staging

jobs:
  build:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9, "3.10", pypy3]

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install coveralls --upgrade
      - name: Run flake8
        run: |
          pip install flake8 --upgrade
          flake8 --exclude=build --ignore=E501,F403,F401,E241,E225,E128 .
      - name: Run pycodestyle
        run: |
          pip install pycodestyle --upgrade
          pycodestyle --ignore=E128,E261,E225,E501,W605 slugify test.py setup.py
      - name: Run test
        run: |
          coverage run --source=slugify test.py
      - name: Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
